INSERT INTO `cybermind`.`user` (`id`, `username`, `password`, `enabled`)
    VALUES ('1', 'user1', '$2a$10$JJdewR3oK93pdv0fGmazGOWsAZlJhWoVTTt.VmPtmFWOLxMa27.Q6', '1');

INSERT INTO `cybermind`.`role` (`id`, `name`) VALUES ('1', 'USER');
INSERT INTO `cybermind`.`role` (`id`, `name`) VALUES ('2', 'ADMIN');

INSERT INTO `cybermind`.`users_roles` (`role_id`, `user_id`) VALUES ('1', '1');

INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('1', 'Riceboard', 'In th eSOLAR Laboratory,the Reply Social Lab,students and Replyers like stop lay table games while', '1234', '2222', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('2', 'Scoreboard', 'There  are  five  problerris,  each  one  requiresto  solve  five different  inputs  of  increasing  score (100,  200,  300,  400  and  500  respectively  for  inputs  one,  two,three,  four  and five).  The  points  for  a specific problem and input will be assigned once perteam.', '444', '1000', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('3', 'Small business', 'A little girl Yulia firmly decided to open her own toy store in the yard. She decided to sell two types of goods: Teddy bears and bunnies. As you know, in any self-respecting store there are price tags. But Yulia, although she is taking her first steps in business, has not yet learned to write. Then she decided to create price tags from the available number of cubes with numbers, using all to the last, so that none was lost. Yulia is very kind, so she decided thatboth prices should form a minimum pair, should not be more than 1018, and may even be equal to zero. However, the concept of leading zeros is repugnant to Yulia, so they should not be on the price tags. Lets support small businesses and help them preparetwo price tags from the available cubes.', '100', '223', '4');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('4', 'Cloud server', 'Running an online contest uses  a  lot  of  hardware   resources,   so  for  the  day   of  the  Reply  Code  Challenge we decide to rent some servers from our trusted provider AWesome Servers (AWSTM).', '60', '100', '3');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('5', 'Items in boxes', 'You have 2ndifferent boxes, each containing adifferent item. Find the number of ways to take exactly one item from each box modulo 2n+2. In other words, if the desired number of ways is x, output the remainder of dividing xby 2n+2.', '25', '50', '2');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('6', 'Quantum teleportation', 'A new team of engineers in Reply is working on a particular kind of quantum computer and wants you to help them!', '10', '50', '1');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('7', 'Riceboard', 'In th eSOLAR Laboratory,the Reply Social Lab,students and Replyers like stop lay table games while', '1234', '2222', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('8', 'Scoreboard', 'There  are  five  problerris,  each  one  requiresto  solve  five different  inputs  of  increasing  score (100,  200,  300,  400  and  500  respectively  for  inputs  one,  two,three,  four  and five).  The  points  for  a specific problem and input will be assigned once perteam.', '444', '1000', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('9', 'Small business', 'A little girl Yulia firmly decided to open her own toy store in the yard. She decided to sell two types of goods: Teddy bears and bunnies. As you know, in any self-respecting store there are price tags. But Yulia, although she is taking her first steps in business, has not yet learned to write. Then she decided to create price tags from the available number of cubes with numbers, using all to the last, so that none was lost. Yulia is very kind, so she decided thatboth prices should form a minimum pair, should not be more than 1018, and may even be equal to zero. However, the concept of leading zeros is repugnant to Yulia, so they should not be on the price tags. Lets support small businesses and help them preparetwo price tags from the available cubes.', '100', '223', '4');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('10', 'Cloud server', 'Running an online contest uses  a  lot  of  hardware   resources,   so  for  the  day   of  the  Reply  Code  Challenge we decide to rent some servers from our trusted provider AWesome Servers (AWSTM).', '60', '100', '3');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('11', 'Items in boxes', 'You have 2ndifferent boxes, each containing adifferent item. Find the number of ways to take exactly one item from each box modulo 2n+2. In other words, if the desired number of ways is x, output the remainder of dividing xby 2n+2.', '25', '50', '2');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('12', 'Quantum teleportation', 'A new team of engineers in Reply is working on a particular kind of quantum computer and wants you to help them!', '10', '50', '1');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('13', 'Riceboard', 'In th eSOLAR Laboratory,the Reply Social Lab,students and Replyers like stop lay table games while', '1234', '2222', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('14', 'Scoreboard', 'There  are  five  problerris,  each  one  requiresto  solve  five different  inputs  of  increasing  score (100,  200,  300,  400  and  500  respectively  for  inputs  one,  two,three,  four  and five).  The  points  for  a specific problem and input will be assigned once perteam.', '444', '1000', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('15', 'Small business', 'A little girl Yulia firmly decided to open her own toy store in the yard. She decided to sell two types of goods: Teddy bears and bunnies. As you know, in any self-respecting store there are price tags. But Yulia, although she is taking her first steps in business, has not yet learned to write. Then she decided to create price tags from the available number of cubes with numbers, using all to the last, so that none was lost. Yulia is very kind, so she decided thatboth prices should form a minimum pair, should not be more than 1018, and may even be equal to zero. However, the concept of leading zeros is repugnant to Yulia, so they should not be on the price tags. Lets support small businesses and help them preparetwo price tags from the available cubes.', '100', '223', '4');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('16', 'Cloud server', 'Running an online contest uses  a  lot  of  hardware   resources,   so  for  the  day   of  the  Reply  Code  Challenge we decide to rent some servers from our trusted provider AWesome Servers (AWSTM).', '60', '100', '3');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('17', 'Items in boxes', 'You have 2ndifferent boxes, each containing adifferent item. Find the number of ways to take exactly one item from each box modulo 2n+2. In other words, if the desired number of ways is x, output the remainder of dividing xby 2n+2.', '25', '50', '2');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('18', 'Quantum teleportation', 'A new team of engineers in Reply is working on a particular kind of quantum computer and wants you to help them!', '10', '50', '1');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('19', 'Riceboard', 'In th eSOLAR Laboratory,the Reply Social Lab,students and Replyers like stop lay table games while', '1234', '2222', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('20', 'Scoreboard', 'There  are  five  problerris,  each  one  requiresto  solve  five different  inputs  of  increasing  score (100,  200,  300,  400  and  500  respectively  for  inputs  one,  two,three,  four  and five).  The  points  for  a specific problem and input will be assigned once perteam.', '444', '1000', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('21', 'Small business', 'A little girl Yulia firmly decided to open her own toy store in the yard. She decided to sell two types of goods: Teddy bears and bunnies. As you know, in any self-respecting store there are price tags. But Yulia, although she is taking her first steps in business, has not yet learned to write. Then she decided to create price tags from the available number of cubes with numbers, using all to the last, so that none was lost. Yulia is very kind, so she decided thatboth prices should form a minimum pair, should not be more than 1018, and may even be equal to zero. However, the concept of leading zeros is repugnant to Yulia, so they should not be on the price tags. Lets support small businesses and help them preparetwo price tags from the available cubes.', '100', '223', '4');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('22', 'Cloud server', 'Running an online contest uses  a  lot  of  hardware   resources,   so  for  the  day   of  the  Reply  Code  Challenge we decide to rent some servers from our trusted provider AWesome Servers (AWSTM).', '60', '100', '3');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('23', 'Items in boxes', 'You have 2ndifferent boxes, each containing adifferent item. Find the number of ways to take exactly one item from each box modulo 2n+2. In other words, if the desired number of ways is x, output the remainder of dividing xby 2n+2.', '25', '50', '2');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('24', 'Quantum teleportation', 'A new team of engineers in Reply is working on a particular kind of quantum computer and wants you to help them!', '10', '50', '1');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('25', 'Riceboard', 'In th eSOLAR Laboratory,the Reply Social Lab,students and Replyers like stop lay table games while', '1234', '2222', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('26', 'Scoreboard', 'There  are  five  problerris,  each  one  requiresto  solve  five different  inputs  of  increasing  score (100,  200,  300,  400  and  500  respectively  for  inputs  one,  two,three,  four  and five).  The  points  for  a specific problem and input will be assigned once perteam.', '444', '1000', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('27', 'Small business', 'A little girl Yulia firmly decided to open her own toy store in the yard. She decided to sell two types of goods: Teddy bears and bunnies. As you know, in any self-respecting store there are price tags. But Yulia, although she is taking her first steps in business, has not yet learned to write. Then she decided to create price tags from the available number of cubes with numbers, using all to the last, so that none was lost. Yulia is very kind, so she decided thatboth prices should form a minimum pair, should not be more than 1018, and may even be equal to zero. However, the concept of leading zeros is repugnant to Yulia, so they should not be on the price tags. Lets support small businesses and help them preparetwo price tags from the available cubes.', '100', '223', '4');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('28', 'Cloud server', 'Running an online contest uses  a  lot  of  hardware   resources,   so  for  the  day   of  the  Reply  Code  Challenge we decide to rent some servers from our trusted provider AWesome Servers (AWSTM).', '60', '100', '3');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('29', 'Items in boxes', 'You have 2ndifferent boxes, each containing adifferent item. Find the number of ways to take exactly one item from each box modulo 2n+2. In other words, if the desired number of ways is x, output the remainder of dividing xby 2n+2.', '25', '50', '2');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('30', 'Quantum teleportation', 'A new team of engineers in Reply is working on a particular kind of quantum computer and wants you to help them!', '10', '50', '1');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('31', 'Riceboard', 'In th eSOLAR Laboratory,the Reply Social Lab,students and Replyers like stop lay table games while', '1234', '2222', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('32', 'Scoreboard', 'There  are  five  problerris,  each  one  requiresto  solve  five different  inputs  of  increasing  score (100,  200,  300,  400  and  500  respectively  for  inputs  one,  two,three,  four  and five).  The  points  for  a specific problem and input will be assigned once perteam.', '444', '1000', '5');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('33', 'Small business', 'A little girl Yulia firmly decided to open her own toy store in the yard. She decided to sell two types of goods: Teddy bears and bunnies. As you know, in any self-respecting store there are price tags. But Yulia, although she is taking her first steps in business, has not yet learned to write. Then she decided to create price tags from the available number of cubes with numbers, using all to the last, so that none was lost. Yulia is very kind, so she decided thatboth prices should form a minimum pair, should not be more than 1018, and may even be equal to zero. However, the concept of leading zeros is repugnant to Yulia, so they should not be on the price tags. Lets support small businesses and help them preparetwo price tags from the available cubes.', '100', '223', '4');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('34', 'Cloud server', 'Running an online contest uses  a  lot  of  hardware   resources,   so  for  the  day   of  the  Reply  Code  Challenge we decide to rent some servers from our trusted provider AWesome Servers (AWSTM).', '60', '100', '3');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('35', 'Items in boxes', 'You have 2ndifferent boxes, each containing adifferent item. Find the number of ways to take exactly one item from each box modulo 2n+2. In other words, if the desired number of ways is x, output the remainder of dividing xby 2n+2.', '25', '50', '2');
INSERT INTO `cybermind`.`task` (`id`, `name`, `description`, `solution`, `views`, `level`) VALUES ('36', 'Quantum teleportation', 'A new team of engineers in Reply is working on a particular kind of quantum computer and wants you to help them!', '10', '50', '1');

